config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  devise_for :users, :controllers => {:registrations => "registrations",
      omniauth_callbacks: "users/omniauth_callbacks"}

  root "pages#home"

  post "/comments/:id", to: "comments#create"
  delete "/comments/:id", to: "comments#destroy"
  get "/search", to: "tours#search"
  post "/search", to: "tours#search"
  post "/likes/:id", to: "likes#create"
  delete "/likes/:id", to: "likes#destroy"
  namespace :admin do
    root "pages#home"
    resources :tours
    resources :categories, except: [:show, :new]
    resources :reviews
    resources :users, except: :edit
  end

  resources :tours, only: %i(index show)
  resources :reviews
  resources :categories, only: :show
  resources :comments, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :users, only: :show
end

app/models/tour.rb
class Tour < ApplicationRecord
  mount_uploader :image, TourImageUploader

  belongs_to :user

  validates :title, presence: true, length: {minimum: Settings.length.title}
  validates :description, presence: true,
    length: {maximum: Settings.length.description}
  validates :content, presence: true, length: {maximum: Settings.length.content}
  validates :price, numericality: {greater_than: Settings.zero},
    allow_nil: true
  validates :date_in, :date_out, presence: true, allow_nil: true
  validate :date_in_before_date_out
  validates :image, presence: true
  UPDATE_ATTRS = [:title, :description, :content, :price, :date_in, :date_out,
    :image].freeze

  scope :newest, ->{order created_at: :desc}

  private

  def date_in_before_date_out
    return unless date_in && date_out

    errors.add(:date_in, I18n.t("err_add.date")) if date_in > date_out
  end
end

app/controllers/admin/tours_controller.rb
class Admin::ToursController < AdminController
  load_and_authorize_resource
  before_action :load_tour, except: %i(index new create)

  def index
    @tours = Tour.order("created_at desc")
  end

  def show; end

  def edit; end

  def new
    @tour = Tour.new
  end

  def create
    @tour = current_user.tours.build tour_params
    if @tour.save
      flash[:info] = t "msg.approved"
      render :show
    else
      render :new
    end
  end

  def update
    @tour.attributes = tour_params
    if @tour.save
      flash[:success] = t "msg.update"
      render :show
    else
      flash[:danger] = t "msg.update_err"
      render :edit
    end
  end

  def destroy
    return unless @tour.destroy
    flash[:success] = t "msg.del"
    redirect_to admin_tours_path
  end

  private

  def tour_params
    params.require(:tour).permit Tour::UPDATE_ATTRS
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :load_tour, only: :show

  def index
    @q = Tour.ransack(params[:q])
    @tours = @q.result.newest.paginate page: params[:page],
      per_page: Settings.tours
  end

  def show; end
end

app/helpers/tours_helper.rb
module ToursHelper
  def full_title page_title
    base_title = I18n.t "base_title"
    return base_title if page_title.blank?

    page_title + " | " + base_title
  end
end

app/views/admin/tours/_form.html.erb
<%= form_for @tour, url: yield(:url) do |f| %>
  <%= render "shared/error_messages", object: f.object  %>

  <%= f.label :title %>
  <%= f.text_field :title, class: "form-control" %>

  <%= f.label :description %>
  <%= f.text_field :description, class: "form-control" %>

  <%= f.label :content %>
  <%= f.text_area :content, class: "form-control" %>

  <%= f.label :price %>
  <%= f.number_field :price, class: "form-control" %>

  <%= f.label :date_in %>
  <%= f.datetime_field :date_in, class: "form-control" %>

  <%= f.label :date_out %>
  <%= f.datetime_field :date_out, class: "form-control" %>

  <%= f.label :image %>
  <%= f.file_field :image %>
  <div class="show-img">
    <% if f.object.image? %>
      <%= image_tag f.object.image %>
    <% end %>
  </div>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/admin/tours/_tour.html.erb
<tr>
  <td><%= tour.id %></td>
  <td><%= tour.title %></td>
  <td><%= tour.description %></td>
  <td><%= image_tag tour.image.url %></td>
  <td><%= link_to t("tours.show.read"), admin_tour_path(tour) %>&emsp;&emsp;
  <%= link_to t("tours.show.edit"), edit_admin_tour_path(tour) %>&emsp;&emsp;
  <%= link_to t("tours.show.del"), admin_tour_path(tour),
    method: :delete, data: { confirm: t("tours.show.confirm") } %>
  </td>
</tr>

app/views/admin/tours/edit.html.erb
<% provide(:button_text, t("tours.edit.save")) %>
<% provide(:title, t("tours.edit.title")) %>
<% provide(:url, admin_tour_path) %>
<div class="row">
  <h4><b> <%= yield :title %><hr/></b></h4>
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/admin/tours/index.html.erb
<% provide :title, t("tours.index.title") %>
<div class="tour container tour-admin">
  <h4><b> <%= yield :title %><hr/></b></h4>
  <%= link_to new_admin_tour_path do %>
    <button class="btn btn-primary btn-add-new">
      <%= t("tours.index.create") %>
    </button>
  <% end %>
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th width="5%"><%= t("table.id") %></th>
        <th width="15%"><%= t("table.title") %></th>
        <th width="35%"><%= t("table.description") %></th>
        <th width="25%"><%= t("table.image") %></th>
        <th width="20%"><%= t("table.action") %></th>
      </tr>
    </thead>
    <tbody>
        <%= render partial: "tour", collection: @tours %>
    </tbody>
  </table>
</div>

app/views/admin/tours/new.html.erb
<% provide(:button_text, t("tours.new.create")) %>
<% provide(:title, t("tours.new.title")) %>
<% provide(:url, admin_tours_path) %>
<div class="row">
  <h4><b> <%= yield :title %><hr/></b></h4>
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/admin/tours/show.html.erb
<% provide :title, @tour.title %>
<div class="tour container">
  <div class="show-tour show-img" >
    <h1><%= yield(:title) %></h1>
    <%= image_tag @tour.image.url %>
    <des><%= @tour.description %></des><hr/>
    <content><%= @tour.content %></content>
  </div>
</div>