config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  devise_for :users, :controllers => {:registrations => "registrations",
      omniauth_callbacks: "users/omniauth_callbacks"}

  root "pages#home"

  post "/comments/:id", to: "comments#create"
  delete "/comments/:id", to: "comments#destroy"
  get "/search", to: "tours#search"
  post "/search", to: "tours#search"
  post "/likes/:id", to: "likes#create"
  delete "/likes/:id", to: "likes#destroy"
  namespace :admin do
    root "pages#home"
    resources :tours
    resources :categories, except: [:show, :new]
    resources :reviews
    resources :users, except: :edit
  end

  resources :tours, only: %i(index show)
  resources :reviews
  resources :categories, only: :show
  resources :comments, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :users, only: :show
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < AdminController
  load_and_authorize_resource
  before_action :load_review, except: %i(new index create)
  before_action :all_reviews, only: [:index, :destroy]

  def index; end

  def show; end

  def new
    @review = Review.new
  end

  def create
    @review = current_user.reviews.build review_params
    if @review.save
      flash[:success] = t "msg.create_review_success"
      render :show
    else
      flash[:danger] = t "msg.create_review_fail"
      render :new
    end
  end

  def edit; end

  def update
    @review.update_attributes review_params
    if @review.save
      flash[:success] = t "msg.update_success"
      redirect_to admin_reviews_path
    else
      flash[:danger] = t "msg.update_fail"
      render :edit
    end
  end

  def destroy
    if @review.destroy
      flash[:success] = t "msg.delete_review_success"
      redirect_to admin_reviews_path
    else
      flash[:danger] = t "msg.delete_review_fail"
      render :index
    end
  end

  private

  def load_review
    @review = Review.find_by id: params[:id]
    return if @review
    flash[:danger] = t "msg.review_invalid"
    redirect_to admin_root_path
  end

  def review_params
    params.require(:review).permit Review::REVIEW_PARAMS
  end

  def all_reviews
    @reviews = Review.newest.paginate page: params[:page],
       per_page: Settings.paginate.reviews
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :user_signed_in?, only: %i(new update edit)
  before_action :load_review, only: %i(show update edit)
  before_action :check_liked, only: :show

  def show
    @comment = Comment.new
    @comments = Comment.includes(:user).select_comments(params[:id])
                       .comment_type Settings.review
    @comments_parent = @comments.comment_id(Settings.parent_id_default).newest
    @comment_type = Settings.review
    @like = Like.new
  end

  def new
    @review = Review.new
  end

  def create
    @review = current_user.reviews.build review_params
    if @review.save
      flash[:success] = t "msg.create_review_success"
      redirect_to @review
    else
      flash[:danger] = t "msg.create_review_fail"
      render :new
    end
  end

  def edit; end

  def update
    @review.assign_attributes review_params
    if @review.save(context: :update_review)
      flash[:success] = t "msg.update_success"
    else
      flash[:danger] = t "msg.update_fail"
    end
    render :edit
  end

  private

  def load_review
    @review = Review.find_by id: params[:id]
    return if @review
    redirect_to root_path
  end

  def review_params
    params.require(:review).permit Review::REVIEW_PARAMS
  end

  def check_liked
    return unless user_signed_in?
    @liked = Like.like_review(params[:id]).find_by user_id: current_user.id
  end
end

app/views/admin/reviews/_form.html.erb
<%= form_for @review, url: url, html: {class: "form-horizontal"} do |f| %>

  <%= render "shared/error_messages", object: f.object %>

  <div class="form-group">
    <%= f.text_field :title, placeholder: t("form.title"), class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_area :description, placeholder: t("form.description"), class: "form-control", rows: Settings.description_row %>
  </div>

  <div class="form-group">
    <%= f.text_area :content, placeholder: t("form.content"), class: "form-control", rows: Settings.content_row %>
  </div>

  <div class="form-group">
      <%= f.select :category_id, f.object.present? ? options_for_select(cate_select, f.object.category_id) : options_for_select(cate_select), class: "form-control"%>
  </div>

  <div class="form-group custom-img">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
    <% if f.object.image? %>
      <%= image_tag f.object.image.url %>
    <% end %>
  </div>

  <div class="form-group">
      <%= f.submit f.object.persisted? ? t("form.update") : t("form.submit"), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/reviews/_review.html.erb
<tr>
  <td><%= review_counter += 1 %></td>
  <td><%= review.title %></td>
  <td class="img-review"><%= image_tag review.image.url %></td>
  <td><%= review.description %></td>
  <td>
    <%= link_to t(".view"), admin_review_path(review.id) %>
    <%= link_to t(".delete"), admin_review_path(review.id), method: :delete, data: { confirm: t("are_you_sure") } %>
    <%= link_to t(".edit"), edit_admin_review_path(review.id) %>
  </td>
</tr>

app/views/admin/reviews/edit.html.erb
<% provide :title, t(".title") %>
<div id="page-content-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2">
        <h1><%= t ".title" %></h1>
        <%= render "form", url: admin_review_path %>
      </div>
    </div>
  </div>
</div>

app/views/admin/reviews/index.html.erb
<% provide :title, t(".title") %>
<div id="page-content-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2">

        <h1><%= t ".title" %></h1>
        <%= link_to new_admin_review_path do %>
          <button type="button" class="btn btn-primary fl-r">
            <%= t ".add_new_review" %>
          </button>
        <% end %>
        <br/> <br/>
        <% if @reviews.any? %>
          <table class="table table-bordered table-hover mt-10">
            <thead>
              <tr>
                <th class="w-5"><%= t ".id" %></th>
                <th class="w-20"><%= t ".title" %> </th>
                <th class="w-20"><%= t ".image" %></th>
                <th class="w-35"><%= t ".descreption" %></th>
                <th class="w-20"><%= t ".action" %></th>
              </tr>
            </thead>
            <tbody>
              <%= render partial: "review", collection: @reviews %>
            </tbody>
          </table>
          <div class="paginate">
            <%= will_paginate @reviews %>
          </div>
        <% else %>
          <i><%= t "msg.no_reviews" %></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/reviews/new.html.erb
<% provide :title, t(".title") %>
<div id="page-content-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2">
        <h1><%= t ".title" %></h1>
        <%= render "form", url: admin_reviews_path %>
      </div>
    </div>
  </div>
</div>

app/views/admin/reviews/show.html.erb
<%= provide :title, t(".title") %>
<div id="page-content-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 show-review">
        <h1 class="rv-title"> <%= @review.title %> </h1>
        <h4> <%= @review.user.full_name %> </h4>
        <br />
        <p class="rv-content"> <%= @review.content %> </p>
        <button class="btn btn-primary"><%= t ".edit" %></button>
        <%= link_to t(".all_review"), admin_reviews_path %>
      </div>
    </div>
  </div>
</div>