config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  devise_for :users, :controllers => {:registrations => "registrations",
      omniauth_callbacks: "users/omniauth_callbacks"}

  root "pages#home"

  post "/comments/:id", to: "comments#create"
  delete "/comments/:id", to: "comments#destroy"
  get "/search", to: "tours#search"
  post "/search", to: "tours#search"
  post "/likes/:id", to: "likes#create"
  delete "/likes/:id", to: "likes#destroy"
  namespace :admin do
    root "pages#home"
    resources :tours
    resources :categories, except: [:show, :new]
    resources :reviews
    resources :users, except: :edit
  end

  resources :tours, only: %i(index show)
  resources :reviews
  resources :categories, only: :show
  resources :comments, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :users, only: :show
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :reviews

  validates :name, presence: true

  scope :newest, ->{order created_at: :desc}
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  load_and_authorize_resource
  before_action :load_category, only: %i(destroy edit update)
  before_action :build_category, only: :index
  before_action :all_categories, only: [:index, :edit]

  def index; end

  def create
    @category = Category.new params_cate
    if @category.save
      flash[:success] = t "msg.create_cate_success"
      redirect_to admin_categories_path
    else
      flash[:danger] = t "msg.create_cate_fail"
      render :index
    end
  end

  def edit
    render :index
  end

  def update
    @category.update_attributes params_cate
    if @category.save
      flash[:success] = t "msg.update_success"
    else
      flash[:danger] = t "msg.update_fail"
    end
    redirect_to admin_categories_path
  end

  def destroy
    if @category.destroy
      flash[:success] =  t "msg.delete_cate_success"
    else
      flash[:danger] = t "msg.delete_cate_fail"
    end
    redirect_to admin_categories_path
  end

  private

  def load_category
    @category = Category.find_by id: params[:id]
    return if @category
    flash[:danger] = t "msg.category_invalid"
    redirect_to root_admin_path
  end

  def params_cate
    params.require(:category).permit :name
  end

  def build_category
    @category = Category.new
  end

  def all_categories
    @categories = Category.newest.paginate page: params[:page],
       per_page: Settings.paginate.categories
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :load_category, only: :show

  def show
    @reviews = @category.reviews.newest
                        .paginate page: params[:page],
                           per_page: Settings.review_page
  end

  private

  def load_category
    @category = Category.find_by id: params[:id]
    return if @category
    flash[:danger] = t "msg.category_invalid"
    redirect_to root_path
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def cate_select
    @categories.map{|cate| [t("nav.#{cate.name}"), cate.id]}
  end
end

app/views/admin/categories/_category.html.erb
<tr>
  <td><%= category_counter += 1 %></td>
  <td><%= category.name %></td>
  <td>
    <%= link_to t(".delete"), admin_category_path(category.id), method: :delete, data: { confirm: t("are_you_sure") } %>
    <%= link_to t(".edit"), edit_admin_category_path(category.id) %>
  </td>
</tr>

app/views/admin/categories/_form.html.erb
<%= form_for @category, url: url, html: {class: "form-inline"} do |f| %>
  <%= f.text_field :name, class: "form-control", placeholder: t(".name") %>
  <% if @category.persisted? %>
    <button class="btn btn-warning">
      <%= t ".update" %>
    </button>
  <% else %>
    <button class="btn btn-primary">
      <%= t ".add_cate" %>
    </button>
  <% end %>
<% end %>

app/views/admin/categories/index.html.erb
<% provide :title, t(".title") %>
<div id="page-content-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2">
        <h1><%= t ".title" %></h1>
        <div class="error-admin">
        </div>
        <div class="category-admin">
          <% if @category.persisted? %>
            <%= render "form", url: admin_category_path(@category.id) %>
          <% else %>
            <%= render "form", url: admin_categories_path %>
          <% end %>
        </div>
        <br/>
        <br/>
        <% if @categories.any? %>
          <table class="table table-bordered table-hover mt-10">
            <thead>
              <tr>
                <th class="w-5"> <%= t ".id" %></th>
                <th class="w-45"> <%= t ".name" %> </th>
                <th class="w-50"> <%= t ".action" %></th>
              </tr>
            </thead>
            <tbody>
              <%= render partial: "category", collection: @categories %>
            </tbody>
          </table>
          <div class="paginate">
            <%= will_paginate @categories %>
          </div>
        <% else %>
          <i><%= t "msg.no_categories" %> </i>
        <% end %>
      </div>
    </div>
  </div>
</div>