config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  devise_for :users, :controllers => {:registrations => "registrations",
      omniauth_callbacks: "users/omniauth_callbacks"}

  root "pages#home"

  post "/comments/:id", to: "comments#create"
  delete "/comments/:id", to: "comments#destroy"
  get "/search", to: "tours#search"
  post "/search", to: "tours#search"
  post "/likes/:id", to: "likes#create"
  delete "/likes/:id", to: "likes#destroy"
  namespace :admin do
    root "pages#home"
    resources :tours
    resources :categories, except: [:show, :new]
    resources :reviews
    resources :users, except: :edit
  end

  resources :tours, only: %i(index show)
  resources :reviews
  resources :categories, only: :show
  resources :comments, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :users, only: :show
end

app/models/user.rb
class User < ApplicationRecord
  USER_PARAMS = %i(email full_name password password_confirmation)
                .freeze
  USER_PARAMS_UPDATE = [:email, :full_name].freeze

  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
    :validatable, :omniauthable, omniauth_providers: [:google_oauth2]

  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :tours
  has_many :likes, dependent: :destroy

  enum role: [:admin, :user]

  scope :newest, ->{order created_at: :desc}

  validates :full_name, presence: true, length: {maximum: 50}

  def self.from_omniauth auth
    user = where(email: auth.info["email"]).first
    return user if user.present?
    password = Devise.friendly_token[0, 20]
    User.create(
      refresh_token: auth.credentials.refresh_token,
      token: auth.credentials.token,
      expires_at: Time.at(auth.credentials.expires_at),
      uid: auth.uid,
      email: auth.info["email"],
      name: auth.info["name"],
      full_name: auth.info["name"],
      google_app_id: ENV["google_app_id"],
      channel_id: ENV["channel_id"],
      password: password,
      password_confirmation: password
    )
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  load_and_authorize_resource
  before_action :load_user, only: [:update, :destroy]
  before_action :all_users, only: :index

  def index; end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = t "msg.create_user_success"
      redirect_to admin_users_path
    else
      flash[:danger] = t "msg.create_user_fail"
      render :new
    end
  end

  def update
    if @user.update_attributes role_params
      flash[:success] = t "msg.update_success"
      redirect_to admin_users_path
    else
      flash[:danger] = t "msg.update_fail"
      all_users
      render :index
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = t "msg.user_delete_success"
    else
      flash[:danger] = t "msg.user_delete_fail"
    end
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit User::USER_PARAMS
  end

  def role_params
    params.require(:user).permit :role
  end

  def load_user
    @user = User.find_by id: params[:id]
    return if @user
    flash[:danger] = t "msg.user_invalid"
    redirect_to admin_users_path
  end

  def all_users
    @users = User.newest.paginate page: params[:page],
       per_page: Settings.paginate.users
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.from_omniauth request.env["omniauth.auth"]
    if @user.nil?
      flash[:danger] = t "devise.omniauth_callbacks.failure"
    else
      flash[:success] = t "devise.omniauth_callbacks.success"
      sign_in @user
    end
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "users_sessions"
  before_action :load_user

  def show; end

  private

  def load_user
    @user = User.find_by id: params[:id]
    return if @user
    flash[:danger] = t "msg.user_invalid"
    redirect_to root_path
  end
end

app/views/admin/users/_user.html.erb
<tr>
  <td><%= user_counter += 1 %></td>
  <td><%= user.full_name %></td>
  <td><%= user.email %></td>
  <td>
    <%= form_for user,url: admin_user_path(user.id), html: {class: "form-inline"} do |f| %>
      <%= f.text_field :role, class: "form-control role-input" %>
      <button class="btn btn-warning"><%= t ".update" %></button>
    <% end %>
  </td>
  <td>
    <%= link_to t(".delete"), admin_user_path(user.id), method: :delete, data: { confirm: t("are_you_sure") } %>

  </td>
</tr>

app/views/admin/users/index.html.erb
<% provide :title, t(".title") %>
<div id="page-content-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2">
        <h1><%= t ".title" %></h1>
        <%= link_to new_admin_user_path do %>
          <button type="button" class="btn btn-primary fl-r">
            <%= t ".add_new_user" %>
          </button>
        <% end %>
        <br/> <br/>
        <table class="table table-bordered table-hover mt-10">
          <thead>
            <tr>
              <th class="w-5" ><%= t ".stt" %></th>
              <th class="w-20"><%= t ".full_name" %> </th>
              <th class="w-20"><%= t ".email" %></th>
              <th class="w-25"><%= t ".role" %></th>
              <th class="w-15"><%= t ".action" %></th>
            </tr>
          </thead>
          <tbody>
            <%= render partial: "user", collection: @users %>
          </tbody>
        </table>
        <div class="paginate">
          <%= will_paginate @users %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/new.html.erb
<% provide :title, t(".title") %>
<div id="page-content-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2">
        <h1><%= t ".title" %> </h1>
        <%= form_for @user, url: admin_users_path, html: {class: "form-horizontal"} do |f| %>
            <%= render "shared/error_messages", object: f.object  %>
            <div class="form-group">
            <%= f.label :email %> (*)
            <%= f.email_field :email, class: "form-control", placeholder: t("email") %>
            </div>
            <div class="form-group">
            <%= f.label :full_name %> (*)
            <%= f.text_field :full_name, class: "form-control", placeholder: t("yourname") %>
            </div>
            <div class="form-group">
            <%= f.label :password %> (*)
            <%= f.password_field :password, class: "form-control", placeholder: t("password") %>
            </div>
            <div class="form-group">
            <%= f.label :password_confirmation %> (*)
            <%= f.password_field :password_confirmation, class: "form-control", placeholder: t("confirm_password") %>
            </div>
            <div class="form-group">
            <%= f.submit t(".add_new_user"), class: "btn btn-primary" %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>